apiVersion: v1
kind: Service
metadata:
  name: news-trend-web
  labels:
    app: news-trend-web
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
  selector:
    app: news-trend-web

